name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v2
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: bun install
      - name: Check formatting
        run: bun run check:format
      - name: Lint check
        run: bun run check:lint
      - name: Check imports
        run: bun run check:imports